language: c
sudo: true
cache:
   directories:
   - ~/arduino_ide
   - ~/.arduino15/packages/
git:
   depth: false
   quiet: true
env:
   global:
   - PRETTYNAME="QuadrupedControl Arduino Library" - INSTALL_PLATFORMS="avr"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/ArminJo/travis-ci-arduino/master/install.sh)
install:
- arduino --install-library "ServoEasing","PinChangeInterrupt","IRLremote","Adafruit NeoPixel","NeoPatterns","PlayRtttl"
# Libraries for the QuadrupedControl example
script:
- build_platform uno
notifications:
   email:
      recipients:
      - armin.arduino@gmail.com
      on_success: always
      on_failure: always